name: guvenle_kirala_study_case
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Bubble
  bubble: ^1.2.1

  #Animations
  animations: ^2.0.7
  lottie: ^2.2.0

  #Responsive Screen
  layout: ^1.0.3

  #Date Format
  intl: ^0.17.0

  #Singleton
  injectable: ^1.5.4
  get: ^4.6.5
  get_it: ^7.2.0

  #Router
  auto_route: ^5.0.4

  #State Management
  provider: ^6.0.5

  #Adobe
  adobe_xd: ^2.0.1

  #SVG
  flutter_svg: ^1.0.3

  #Localization
  flutter_localization: ^0.1.10

  #Google Fonts
  google_fonts: ^4.0.3

  #Logger
  logger: ^1.2.2

  #Auto Size Text
  auto_size_text: ^3.0.0

  #Cached Network Image
  cached_network_image: ^3.2.3
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  #Base Template View and ViewModel
  injectable_generator: ^1.5.4
  #Auto Route Generator
  auto_route_generator: ^5.0.3

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo/
    - lib/assets/lottie/
    - lib/assets/image/

flutter_intl:
  enabled: true
